package tech.ssemaj.poseidon.runtime

import android.content.Context
import android.util.Log
import androidx.startup.Initializer
import org.json.JSONObject

/**
 * Loads the compiled policy (poseidon/policy.json, generated by the Gradle plugin
 * from DSL + YAML) at process start and configures PolicyEngine + Mode. Runs with
 * zero app code via androidx.startup (registered in this library's manifest).
 */
class PoseidonInitializer : Initializer<Unit> {
    override fun create(context: Context) {
        try {
            val json = context.assets.open("poseidon/policy.json")
                .bufferedReader().use { it.readText() }
            val o = JSONObject(json)
            Mode.current = if (o.optString("mode") == "enforce") Mode.ENFORCE else Mode.MONITOR
            val hosts = o.strings("allowedHosts")
            PolicyEngine.configure(hosts, o.strings("deniedPaths"))
            // Push the host allow-list into the native shim (covers native SDK traffic).
            NativeBridge.apply(hosts, Mode.current == Mode.ENFORCE)
            // Install the seccomp connect() gate — covers Go/raw-syscall (below libc).
            // ENFORCE implies DNS correlation (guarantee posture: default-deny by name
            // across raw/Go DNS too); MONITOR honors the explicit opt-in flag.
            val enforcing = Mode.current == Mode.ENFORCE
            NativeBridge.installSeccompGate(enforcing || o.optBoolean("dnsCorrelation", false))
            Log.i(
                "Poseidon",
                "policy loaded: mode=${Mode.current}, " +
                    "${o.strings("allowedHosts").size} allowed host(s), " +
                    "${o.strings("deniedPaths").size} denied path(s)",
            )
        } catch (e: Exception) {
            Log.w("Poseidon", "no policy asset found; running open (${e.message})")
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = emptyList()

    private fun JSONObject.strings(key: String): List<String> {
        val arr = optJSONArray(key) ?: return emptyList()
        return (0 until arr.length()).map { arr.getString(it) }
    }
}
