package tech.ssemaj.poseidon.runtime.config

import android.content.Context
import android.util.Log
import androidx.startup.Initializer
import tech.ssemaj.poseidon.runtime.internal.PoseidonConstants.LOG_TAG

/**
 * Loads the compiled policy (poseidon/policy.json, generated by the Gradle plugin
 * from DSL + YAML) at process start and configures PolicyEngine + Mode. Runs with
 * zero app code via androidx.startup (registered in this library's manifest).
 */
class PoseidonInitializer : Initializer<Unit> {
    override fun create(context: Context) {
        // Discover the optional native backend (poseidon-native). Triggers NativeShimBackend's
        // object init -> loadLibrary + NativeBridge.register(this). Absent in JVM-only builds.
        runCatching { Class.forName("tech.ssemaj.poseidon.runtime.NativeShimBackend") }
        try {
            val config = PolicyAssetLoader.load(context)
            PolicyInstaller.install(config)
            with(config) {
                Log.i(
                    LOG_TAG,
                    "policy loaded: mode=$mode, ${allowedHosts.size} allowed host(s), " +
                        "${deniedPaths.size} denied path(s), ${allowedCidrs.size} allowed CIDR(s)",
                )
            }
        } catch (e: Exception) {
            Log.w(LOG_TAG, "no policy asset found; running open (${e.message})")
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = emptyList()
}
