package tech.ssemaj.poseidon.runtime.config

import android.content.Context
import android.util.Log
import androidx.startup.Initializer

/**
 * Loads the compiled policy (poseidon/policy.json, generated by the Gradle plugin
 * from DSL + YAML) at process start and configures PolicyEngine + Mode. Runs with
 * zero app code via androidx.startup (registered in this library's manifest).
 */
class PoseidonInitializer : Initializer<Unit> {
    override fun create(context: Context) {
        // Discover the optional native backend (poseidon-native). Triggers NativeShimBackend's
        // object init -> loadLibrary + NativeBridge.register(this). Absent in JVM-only builds.
        try { Class.forName("tech.ssemaj.poseidon.runtime.NativeShimBackend") } catch (_: Throwable) {}
        try {
            val config = PolicyAssetLoader.load(context)
            PolicyInstaller.install(config)
            Log.i(
                "Poseidon",
                "policy loaded: mode=${config.mode}, " +
                    "${config.allowedHosts.size} allowed host(s), " +
                    "${config.deniedPaths.size} denied path(s), " +
                    "${config.allowedCidrs.size} allowed CIDR(s)",
            )
        } catch (e: Exception) {
            Log.w("Poseidon", "no policy asset found; running open (${e.message})")
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = emptyList()
}
